language: c
sudo: required
dist: trusty
before_install:
- pwd
install:
- pwd
- cd /home/travis/build/hurwitzlab/imicrobe-puca
- curl -k -u ${AGAVE_CREDENTIALS} -d grant_type=client_credentials -d scope=PRODUCTION https://agave.iplantc.org/token
script:
- pwd
- ls -l
env:
  global:
    secure: gSPUXfwRocZO5gu7jCKKJA+o1KcuSR9CkUkOeKrD+2y3oX+s2eY/fi0zaWDv4V33aDgY+g9cezUJmwLIpzXeN/Zyf8l69U+4kg2zPq6VM5X9Ce1cUt6TtbzUryXbyaDZd4Izo8G42zsJf09gVOqEhjMuCgBam3KumwSA2r1j8CzhHXt0qWhaFP6XCfBOdBhk4nJMIG+Jeb+d00T+EqPO3Ue4CCpj7Ax9VKjMikCTILlwnIIxSFDaDPU07f6XZLC1yT49uCqAs9eVbuelZ+JV+j3kpIY2UshJMsHx/6/PeieafZKpvYxWRsOTNA9V0SxZ4UxUiKbQyuZTi8XH9uhgugCHJUFuiUlkYQ68yc6ZkBhYEowKghFvCLE40HPH8qunz52+e08pyDdlZOrazI51YaTAa1MRaSaZkMIylBwP6IfjjXtxEs3nZueonGEnZEHWnMzTdBXX3d5vZ/amkDyggO4ZhaLYdeqRAL259aDaFcW39gn3BPQbteuelpOSn66dt7xSo4s9qgsnzpt8GqUmAy7nQocRvt8y+RBmwj/1BCRc/8F16syT+jXoOXafUpOQ2laYzs6u7d/HIqlX5E6Df8sQR3slENyZ7gDVljKuALnJ5gYcIKx3/hbPvYrm7uHawafAtdcnMGGAMKx6zg/ja9WX1wRAUuKQmjYmuqLNpjo=
notifications:
  slack:
    secure: QcajAkLz1aUhGys4BAlhK3rs+wyC4M8tdiFVpVhNrUDbjJUOjTrjmPS5RX2sTlmyVtfHsD/v3pezqAJJSc3fkaLOisaj3BPUG3btMCGHIi/oHGQV7V48IgcgSA5X45huj8Bltn0n2kwfKlRJaJj4JUbEimWJepBnGdeZ+cm2PcGmUU/OsFGrft23qW3ykb+tD0KSSGlzzqpWKjg6pHpIwzXOFR3Z2YoNQJ5HmEUQfkBM9G75UjvDuAgseRzPn4U0FDzODLP44jDYtza8g8+qw4f0bsXPcMRTdlUb67fN5G0t1QVhvt9fWaN/flFhZwmIydHRFQOHgFVInTcNmGrYSXwH+qnTnijUGz+6QYxeZPva+VqhFTCtxNq5SEM+0LmrkWsmAVYAGyAEr8Sm/oBp8aLW25zSIOw9jRWcrIMRrgiiirn9ODrOM4f4doM++IY1vuGCZzlDlVBni6S1fWoo2j9nrXPbA7SBnXTmNsIX5213fBASp1HmSzDQ/7HWFpHamzfQonwa8eJ/GPhr9I01W/xNtr3eqxGZNmXVtfPRkmXFsovuSs582DFeWrK1e4pULqoGPro9cBtVjliD99QDOwOv2qGPhxvmbxoj3iD29EwP5PeSHRlQc9sugAXeyJ31Kb7hbShVb+G5r2PM08TscX0w0gjJJAnNt8roATwVLlc=
