language: c
sudo: required
dist: trusty
before_install:
- pwd
install:
- pwd
- cd /home/travis/build/hurwitzlab/imicrobe-puca
- curl -k -u ${AGAVE_CREDENTIALS} -d grant_type=client_credentials -d scope=PRODUCTION https://agave.iplantc.org/token
script:
- pwd
- ls -l
env:
  global:
    secure: gSPUXfwRocZO5gu7jCKKJA+o1KcuSR9CkUkOeKrD+2y3oX+s2eY/fi0zaWDv4V33aDgY+g9cezUJmwLIpzXeN/Zyf8l69U+4kg2zPq6VM5X9Ce1cUt6TtbzUryXbyaDZd4Izo8G42zsJf09gVOqEhjMuCgBam3KumwSA2r1j8CzhHXt0qWhaFP6XCfBOdBhk4nJMIG+Jeb+d00T+EqPO3Ue4CCpj7Ax9VKjMikCTILlwnIIxSFDaDPU07f6XZLC1yT49uCqAs9eVbuelZ+JV+j3kpIY2UshJMsHx/6/PeieafZKpvYxWRsOTNA9V0SxZ4UxUiKbQyuZTi8XH9uhgugCHJUFuiUlkYQ68yc6ZkBhYEowKghFvCLE40HPH8qunz52+e08pyDdlZOrazI51YaTAa1MRaSaZkMIylBwP6IfjjXtxEs3nZueonGEnZEHWnMzTdBXX3d5vZ/amkDyggO4ZhaLYdeqRAL259aDaFcW39gn3BPQbteuelpOSn66dt7xSo4s9qgsnzpt8GqUmAy7nQocRvt8y+RBmwj/1BCRc/8F16syT+jXoOXafUpOQ2laYzs6u7d/HIqlX5E6Df8sQR3slENyZ7gDVljKuALnJ5gYcIKx3/hbPvYrm7uHawafAtdcnMGGAMKx6zg/ja9WX1wRAUuKQmjYmuqLNpjo=
notifications:
  slack:
    secure: rFMbRrfhKfxGastwyBKiW9fQEFJKvk76O3VNZeLq7wT0JwI+nD97LQmA1F0Gy3UgznubV0HoYYEyYJOhXsimolpSEa7rR4cwz45dTqGR+9W+bgHLhXM1dnH7JYj8YR2UdEAjhMOGNcO0mmhDf21Xjnv5/Ll9ZbZSScY6WUkmiqPm21iAs0hEby/V2KllE2ZEpHOVrCEOe9QexHncTfF8Yu07wld7rS2wALDURU2SKF4+oYWP84d6pu8TOMFzY6ehNp2QgKdklCb1K74XRmT85HvF8CeNimPnEWADqBSQc6xdI0fnFdvtqtcz13Knu5+riLU9v1d7jYxD4C3vAzcYlM8sJHvlzOThAGW6ph9U/V0yAYXoEkffobumYZYVBwCAhNMpO4D4UP4mEJok2KBc8L3GYLE0j/ozqfuAEkNMoSd/JOX0PvmjheBkAojT1GJjEfaivVGnsdLsfILtB47OHMbe+o800dj4S1JHSe+C7ub/j+SQt5RVIlBUNOjXicLLlLXtOFSSHbxCqIg5/zq5iv+jwTA23udEo/Z/zAd98Whn1zSGZu5FDVd4RVSqnu1c+GUD3iA4P+ptQSuAcBJ6LAJ6/wqW2zuo/0Hv2A9KbFzytkpOh0J/e+u4UgkmCjqUoqfLlagFjWaah5kcOeSgFNGZmZ5LE0myZMVQxCfWwVA=
